# Generated by Django 4.2 on 2023-05-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Объект избранного', 'verbose_name_plural': 'Объекты избранного'},
        ),
    ]
