# Generated by Django 4.2 on 2023-05-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscribers_author_alter_subscribers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['-id']},
        ),
    ]
